export const listData = [
  {
    id: 1,
    title: "A Great Apartment Next to the Beach",
    img: "https://www.pexels.com/photo/modern-building-against-sky-323780/",

    badroom: 2,
    bathroom: 1,
    price: 1000,
    address: "420 morris road, Melbourne",
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 2,
    title: "A Great Apartment Next to the Beach",
    img: "https://www.pexels.com/photo/house-lights-turned-on-106399/",
    badroom: 2,
    bathroom: 1,
    price: 1000,
    address: "420 morris road, Melbourne",
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 3,
    title: "A Great Apartment Next to the Beach",
    img: "https://www.pexels.com/photo/white-and-red-wooden-house-with-fence-1029599/",
    badroom: 2,
    bathroom: 1,
    price: 1000,
    address: "420 morris road, Melbourne",
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 4,
    title: "A Great Apartment Next to the Beach",
    img: "https://www.pexels.com/photo/lighted-beige-house-1396132/",
    badroom: 2,
    bathroom: 1,
    price: 1000,
    address: "420 morris road, Melbourne",
    latitude: 51.5074,
    longitude: -0.1278,
  },
];
