export const listData = [
  {
    id: 1,
    title: "A Great Apartment Next to the Beach",
    img: "https://www.pexels.com/photo/modern-building-against-sky-323780/",

    bedRooms: 2,
    bathRooms: 1,
    price: 1000,
    address: "420 morris road, Melbourne",
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 2,
    title: "A Great Apartment Next to the Beach",
    img: "https://www.pexels.com/photo/house-lights-turned-on-106399/",
    bedRooms: 2,
    bathRooms: 1,
    price: 1000,
    address: "420 morris road, Melbourne",
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 3,
    title: "A Great Apartment Next to the Beach",
    img: "https://www.pexels.com/photo/white-and-red-wooden-house-with-fence-1029599/",
    bedRooms: 2,
    bathRooms: 1,
    price: 1000,
    address: "420 morris road, Melbourne",
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 4,
    title: "A Great Apartment Next to the Beach",
    img: "https://www.pexels.com/photo/lighted-beige-house-1396132/",
    bedRooms: 2,
    bathRooms: 1,
    price: 1000,
    address: "420 morris road, Melbourne",
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 5,
    title: "A Great Apartment Next to the Beach",
    img: "https://www.pexels.com/photo/white-wooden-cupboards-2724749/",
    bedRooms: 2,
    bathRooms: 1,
    price: 1000,
    address: "420 morris road, Melbourne",
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 6,
    title: "A Great Apartment Next to the Beach",
    img: "https://www.pexels.com/photo/bedroom-2631746/",
    bedRooms: 2,
    bathRooms: 1,
    price: 1000,
    address: "420 morris road, Melbourne",
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 7,
    title: "A Great Apartment Next to the Beach",
    img: "https://www.pexels.com/photo/white-wooden-building-53610/",
    bedRooms: 2,
    bathRooms: 1,
    price: 1000,
    address: "420 morris road, Melbourne",
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 8,
    title: "A Great Apartment Next to the Beach",
    img: "https://www.pexels.com/photo/white-concrete-house-under-sky-259685/",

    bedRooms: 2,
    bathRooms: 1,
    price: 1000,
    address: "420 morris road, Melbourne",
    latitude: 51.5074,
    longitude: -0.1278,
  },
];
